# TrustformeRS Markdown Linting Configuration

# Default state for all rules
default: true

# Line length
MD013:
  line_length: 100
  heading_line_length: 100
  code_block_line_length: 100
  code_blocks: false
  tables: false
  headings: true
  headers: true
  strict: false
  stern: false

# Heading style
MD003:
  style: "atx"

# Unordered list style
MD004:
  style: "dash"

# Ordered list item prefix
MD029:
  style: "ordered"

# Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# Code block style
MD046:
  style: "fenced"

# Emphasis style
MD049:
  style: "asterisk"

# Strong style
MD050:
  style: "asterisk"

# Allow inline HTML
MD033:
  allowed_elements:
    - "details"
    - "summary"
    - "sup"
    - "sub"
    - "br"
    - "img"
    - "a"
    - "code"
    - "pre"
    - "table"
    - "thead"
    - "tbody"
    - "tr"
    - "td"
    - "th"
    - "div"
    - "span"
    - "p"
    - "blockquote"
    - "ul"
    - "ol"
    - "li"
    - "h1"
    - "h2"
    - "h3"
    - "h4"
    - "h5"
    - "h6"

# Allow duplicate headings
MD024:
  siblings_only: true

# Allow trailing punctuation in headings
MD026:
  punctuation: ".,;:!"

# Allow multiple spaces after blockquote symbol
MD027: false

# Allow multiple spaces after hash on atx style heading
MD019: false

# Don't require blank lines around lists
MD032: false

# Allow bare URLs
MD034: false

# First line in file should be a top level heading
MD041: false

# Disable rules that conflict with prettier or common practices
MD010: false  # Hard tabs
MD012: false  # Multiple consecutive blank lines
MD022: false  # Headings should be surrounded by blank lines
MD031: false  # Fenced code blocks should be surrounded by blank lines
MD040: false  # Code blocks should have a language specified

# Custom rules for documentation
MD025: true   # Multiple top-level headings
MD042: false  # URLs should be relative