# TrustformeRS YAML Linting Configuration

extends: default

rules:
  # Line length
  line-length:
    max: 120
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Brackets
  brackets:
    max-spaces-inside: 1
    min-spaces-inside: 0
    max-spaces-inside-empty: 0

  # Braces
  braces:
    max-spaces-inside: 1
    min-spaces-inside: 0
    max-spaces-inside-empty: 0

  # Colons
  colons:
    max-spaces-before: 0
    max-spaces-after: 1

  # Commas
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1

  # Comments
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1

  # Document start/end
  document-start: disable
  document-end: disable

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0

  # Empty values
  empty-values: enable

  # Hyphens
  hyphens:
    max-spaces-after: 1

  # Key duplicates
  key-duplicates: enable

  # Key ordering
  key-ordering: disable

  # New line at end of file
  new-line-at-end-of-file: enable

  # New lines
  new-lines:
    type: unix

  # Octal values
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: false

  # Quoted strings
  quoted-strings:
    quote-type: double
    required: only-when-needed
    extra-required: []
    extra-allowed: []
    allow-quoted-quotes: false

  # Trailing spaces
  trailing-spaces: enable

  # Truthy values
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: true
    level: warning

# File ignore patterns
ignore: |
  target/
  vendor/
  third_party/
  .git/
  node_modules/
  dist/
  build/