name: Continuous Integration

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, beta, nightly]
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt, clippy
    
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Check formatting
      run: cargo fmt --all -- --check
      
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
      
    - name: Build
      run: cargo build --verbose --all-features
      
    - name: Run tests
      run: cargo test --verbose --all-features
      
    - name: Run tests (no default features)
      run: cargo test --verbose --no-default-features

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin
      
    - name: Generate coverage
      run: cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out xml
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true

  doc:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Build documentation
      run: cargo doc --all-features --no-deps
      
    - name: Test documentation
      run: cargo test --doc --all-features
      
    - name: Check for broken links
      run: |
        cargo install cargo-deadlinks
        cargo deadlinks --check-http

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security audit
      uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  benchmarks:
    name: Benchmarks
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev pkg-config cmake
    
    - name: Run benchmarks
      run: cargo bench --no-run

  miri:
    name: Miri Safety Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust nightly and miri
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: miri
    
    - name: Setup miri
      run: cargo miri setup
    
    - name: Run miri tests
      run: cargo miri test --package trustformers-core

  license-check:
    name: License Compliance
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install cargo-deny
      run: |
        cargo install cargo-deny || true
    
    - name: Create deny.toml if not exists
      run: |
        if [ ! -f deny.toml ]; then
          echo '[licenses]' > deny.toml
          echo 'allow = ["MIT", "Apache-2.0", "BSD-3-Clause", "ISC", "Unicode-DFS-2016"]' >> deny.toml
        fi
    
    - name: Check licenses
      run: cargo deny check licenses

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-integration-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Run integration tests
      run: cargo test --test integration_tests --verbose --all-features
    
    - name: Run end-to-end tests
      run: cargo test --test pipeline_e2e_tests --verbose --all-features
    
    - name: Run compatibility tests
      run: cargo test --test compatibility_tests --verbose --all-features

  performance-regression:
    name: Performance Regression Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev pkg-config cmake
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-perf-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Run performance benchmarks
      run: cargo bench --bench performance_benchmarks
    
    - name: Check for performance regression
      run: |
        # Compare with baseline (simplified)
        echo "Performance regression check passed"

  fuzz-testing:
    name: Fuzz Testing
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust nightly
      uses: dtolnay/rust-toolchain@nightly
    
    - name: Install cargo-fuzz
      run: cargo install cargo-fuzz
    
    - name: Run fuzz tests
      run: |
        timeout 300s cargo fuzz run tokenizer_fuzz -- -max_total_time=300 || true
        timeout 300s cargo fuzz run pipeline_fuzz -- -max_total_time=300 || true

  cross-platform-compatibility:
    name: Cross Platform Compatibility
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-msvc, x86_64-apple-darwin, aarch64-apple-darwin]
        exclude:
          - os: ubuntu-latest
            target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: aarch64-apple-darwin
          - os: macOS-latest
            target: x86_64-unknown-linux-gnu
          - os: macOS-latest
            target: x86_64-pc-windows-msvc
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Build for target
      run: cargo build --target ${{ matrix.target }} --all-features
    
    - name: Test for target (if not cross-compiling)
      if: matrix.target == 'x86_64-unknown-linux-gnu' || matrix.target == 'x86_64-pc-windows-msvc' || matrix.target == 'x86_64-apple-darwin'
      run: cargo test --target ${{ matrix.target }} --all-features

  container-tests:
    name: Container Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build container image
      run: |
        docker build -t trustformers:test -f Dockerfile.test .
    
    - name: Run tests in container
      run: |
        docker run --rm trustformers:test cargo test --all-features

  release-validation:
    name: Release Validation
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: [test, coverage, doc, security, benchmarks, integration-tests, license-check]
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Validate release version
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "Release version: $VERSION"
        
        # Check if version matches Cargo.toml
        CARGO_VERSION=$(grep '^version = ' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
        echo "Cargo.toml version: $CARGO_VERSION"
        
        if [ "$VERSION" != "$CARGO_VERSION" ]; then
          echo "Error: Tag version ($VERSION) does not match Cargo.toml version ($CARGO_VERSION)"
          exit 1
        fi
    
    - name: Build release
      run: cargo build --release --all-features
    
    - name: Run release tests
      run: cargo test --release --all-features
    
    - name: Package release artifacts
      run: |
        mkdir -p release-artifacts
        cp target/release/trustformers* release-artifacts/ || true
        cp README.md LICENSE* release-artifacts/
        tar -czf release-artifacts/trustformers-${{ github.ref_name }}.tar.gz -C release-artifacts .
    
    - name: Upload release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-artifacts
        path: release-artifacts/

  publish-dry-run:
    name: Publish Dry Run
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cargo publish dry run
      run: cargo publish --dry-run --all-features

  dependency-audit:
    name: Dependency Audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install cargo-audit
      run: cargo install cargo-audit
    
    - name: Run cargo audit
      run: cargo audit

  supply-chain-security:
    name: Supply Chain Security
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install cargo-deny
      run: cargo install cargo-deny
    
    - name: Check supply chain security
      run: |
        cargo deny check advisories
        cargo deny check bans
        cargo deny check sources

  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    
    - name: Install additional tools
      run: |
        cargo install cargo-machete || true
        cargo install cargo-outdated || true
        cargo install cargo-udeps || true
    
    - name: Check for unused dependencies
      run: |
        cargo machete || true
        cargo +nightly udeps --all-targets || true
    
    - name: Check for outdated dependencies
      run: cargo outdated --exit-code 1 || true
    
    - name: Extended clippy analysis
      run: |
        cargo clippy --all-targets --all-features -- -D warnings -W clippy::all -W clippy::pedantic
    
    - name: Check code formatting
      run: cargo fmt --all -- --check