name: Pull Request Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-C link-arg=-fuse-ld=lld -D warnings"
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

jobs:
  # Quick format and lint checks
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-
      
      - name: Check formatting
        run: cargo fmt --all -- --check
      
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  # Security audit
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install cargo-audit
        run: cargo install cargo-audit
      
      - name: Run security audit
        run: cargo audit

  # Test matrix across different platforms and Rust versions
  test:
    name: Test (${{ matrix.os }}, Rust ${{ matrix.rust }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable, beta]
        include:
          - os: ubuntu-latest
            rust: nightly
          - os: windows-latest
            rust: stable
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      
      - name: Install system dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config cmake
      
      - name: Install system dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install cmake
      
      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-${{ matrix.rust }}-
            ${{ runner.os }}-cargo-build-
      
      - name: Install nextest
        run: |
          curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
        if: matrix.os == 'ubuntu-latest'
      
      - name: Install nextest (macOS)
        run: |
          curl -LsSf https://get.nexte.st/latest/mac | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
        if: matrix.os == 'macos-latest'
      
      - name: Install nextest (Windows)
        run: |
          $tmp = New-TemporaryFile | Rename-Item -NewName { $_.Name -replace '$', '.zip' } -PassThru
          Invoke-WebRequest -Uri https://get.nexte.st/latest/windows -OutFile $tmp
          $outputDir = if ($Env:CARGO_HOME) { Join-Path $Env:CARGO_HOME "bin" } else { "~/.cargo/bin" }
          $tmp | Expand-Archive -DestinationPath $outputDir -Force
          $tmp | Remove-Item
        if: matrix.os == 'windows-latest'
        shell: powershell
      
      - name: Run tests
        run: cargo nextest run --no-fail-fast
      
      - name: Run doctests
        run: cargo test --doc

  # Feature flag tests
  feature-tests:
    name: Feature Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - ""  # default features
          - "cuda"
          - "metal"
          - "wasm"
          - "mobile"
          - "all"
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config cmake
      
      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-features-${{ matrix.features }}-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Test with features
        run: |
          if [ "${{ matrix.features }}" = "" ]; then
            cargo test
          elif [ "${{ matrix.features }}" = "all" ]; then
            cargo test --all-features
          else
            cargo test --features "${{ matrix.features }}"
          fi

  # Workspace member tests
  workspace-tests:
    name: Workspace Tests - ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - trustformers-core
          - trustformers-models
          - trustformers-optim
          - trustformers-data
          - trustformers-tokenizers
          - trustformers-training
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config cmake
      
      - name: Test workspace member
        run: cargo test -p ${{ matrix.package }}

  # Documentation build test
  doc-test:
    name: Documentation Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Build documentation
        run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: "-D warnings"

  # Benchmark comparison (non-blocking)
  benchmark:
    name: Performance Check
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config cmake
          cargo install cargo-criterion
      
      - name: Checkout base branch
        run: |
          git fetch origin ${{ github.base_ref }}
          git checkout origin/${{ github.base_ref }}
      
      - name: Run base benchmarks
        run: |
          cargo criterion --message-format=json > base-benchmarks.json
      
      - name: Checkout PR branch
        run: |
          git checkout ${{ github.sha }}
      
      - name: Run PR benchmarks
        run: |
          cargo criterion --message-format=json > pr-benchmarks.json
      
      - name: Compare benchmarks
        run: |
          echo "## Benchmark Comparison" >> $GITHUB_STEP_SUMMARY
          echo "Comparing performance between base and PR..." >> $GITHUB_STEP_SUMMARY
          # Add comparison logic here

  # Integration tests
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config cmake
      
      - name: Run integration tests
        env:
          REDIS_URL: redis://localhost:6379
        run: |
          cargo test --test '*' --features integration-tests

  # Code coverage
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      
      - name: Generate coverage
        run: |
          cargo tarpaulin --out xml --all-features --workspace \
            --exclude trustformers-py \
            --timeout 600
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./cobertura.xml
          fail_ci_if_error: false

  # Final status check
  pr-status:
    name: PR Status Check
    runs-on: ubuntu-latest
    needs: [lint, security, test, feature-tests, workspace-tests, doc-test, integration]
    if: always()
    steps:
      - name: Check all tests passed
        run: |
          if [[ "${{ needs.lint.result }}" != "success" || \
                "${{ needs.security.result }}" != "success" || \
                "${{ needs.test.result }}" != "success" || \
                "${{ needs.feature-tests.result }}" != "success" || \
                "${{ needs.workspace-tests.result }}" != "success" || \
                "${{ needs.doc-test.result }}" != "success" || \
                "${{ needs.integration.result }}" != "success" ]]; then
            echo "One or more required checks failed"
            exit 1
          fi
          echo "All required checks passed!"