name: Python Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

env:
  PACKAGE_PATH: trustformers-py

defaults:
  run:
    working-directory: trustformers-py

jobs:
  # Update Python dependencies
  update-python-dependencies:
    name: Update Python Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependency management tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools pipdeptree safety

      - name: Check current dependencies
        run: |
          echo "## Current Dependencies" >> $GITHUB_STEP_SUMMARY
          if [ -f requirements.txt ]; then
            echo "### requirements.txt" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat requirements.txt >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -f pyproject.toml ]; then
            echo "### pyproject.toml dependencies" >> $GITHUB_STEP_SUMMARY
            echo '```toml' >> $GITHUB_STEP_SUMMARY
            grep -A 20 "dependencies" pyproject.toml || echo "No dependencies section found" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi

      - name: Update development dependencies
        run: |
          # Create or update requirements files
          cat > requirements-dev.in << 'EOF'
          # Development dependencies
          pytest>=7.0.0
          pytest-cov>=4.0.0
          pytest-asyncio>=0.20.0
          pytest-xdist>=3.0.0
          pytest-benchmark>=4.0.0
          
          # Code quality
          black>=23.0.0
          isort>=5.12.0
          flake8>=6.0.0
          mypy>=1.0.0
          bandit>=1.7.0
          pylint>=2.15.0
          ruff>=0.1.0
          
          # Build tools
          maturin>=1.0.0
          build>=0.10.0
          wheel>=0.40.0
          
          # Security
          safety>=2.3.0
          pip-audit>=2.6.0
          
          # Documentation
          sphinx>=6.0.0
          sphinx-rtd-theme>=1.2.0
          myst-parser>=0.18.0
          
          # Optional heavy dependencies (for testing)
          torch>=2.0.0; platform_machine != "arm64"
          jax[cpu]>=0.4.0; platform_machine != "arm64"
          tensorflow>=2.13.0; platform_machine != "arm64"
          
          # ML/Data science
          numpy>=1.24.0
          pandas>=2.0.0
          scikit-learn>=1.3.0
          matplotlib>=3.7.0
          seaborn>=0.12.0
          plotly>=5.15.0
          
          # MLOps
          mlflow>=2.5.0
          wandb>=0.15.0
          tensorboard>=2.13.0
          
          # Serving
          fastapi>=0.100.0
          uvicorn>=0.23.0
          prometheus-client>=0.17.0
          
          # Jupyter
          jupyter>=1.0.0
          ipywidgets>=8.0.0
          tqdm>=4.65.0
          EOF
          
          # Generate locked requirements
          pip-compile requirements-dev.in --upgrade --generate-hashes

      - name: Check for security vulnerabilities
        run: |
          echo "## Security Check" >> $GITHUB_STEP_SUMMARY
          
          # Check installed packages
          pip freeze > current-requirements.txt
          safety check --file current-requirements.txt --json --output safety-report.json || true
          
          if [ -f safety-report.json ]; then
            echo "### Safety Report" >> $GITHUB_STEP_SUMMARY
            echo '```json' >> $GITHUB_STEP_SUMMARY
            head -n 50 safety-report.json >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi
          
          # Run pip-audit
          pip-audit --format=json --output=audit-report.json . || true
          
          if [ -f audit-report.json ]; then
            echo "### Audit Report" >> $GITHUB_STEP_SUMMARY
            echo '```json' >> $GITHUB_STEP_SUMMARY
            head -n 30 audit-report.json >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi

      - name: Update GitHub Actions versions
        run: |
          # Update GitHub Actions in all workflow files
          cd ../.github/workflows
          
          # Common action updates
          sed -i 's/actions\/checkout@v3/actions\/checkout@v4/g' *.yml
          sed -i 's/actions\/setup-python@v3/actions\/setup-python@v4/g' *.yml
          sed -i 's/actions\/cache@v3/actions\/cache@v3/g' *.yml  # Keep v3 for compatibility
          sed -i 's/codecov\/codecov-action@v3/codecov\/codecov-action@v4/g' *.yml
          
          echo "Updated GitHub Actions versions"

      - name: Check dependency tree
        run: |
          # Install requirements and check dependency tree
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          fi
          
          echo "## Dependency Tree" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          pipdeptree --warn silence | head -n 100 >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Test with updated dependencies
        run: |
          # Set up Rust for building
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source ~/.cargo/env
          
          # Try to build the package
          if command -v maturin &> /dev/null; then
            echo "Testing build with updated dependencies..."
            maturin develop || echo "Build failed with updated dependencies"
          fi

      - name: Create pull request
        id: create_pr
        run: |
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "Dependency Update Bot"
          
          # Check if there are changes
          if ! git diff --quiet; then
            # Create branch
            branch_name="update-python-dependencies-$(date +%Y%m%d)"
            git checkout -b "$branch_name"
            
            # Add changes
            git add .
            git add ../.github/workflows/*.yml
            
            # Commit changes
            commit_message="Update Python dependencies and GitHub Actions

            - Updated development dependencies to latest versions
            - Updated GitHub Actions to latest stable versions
            - Ran security checks on dependencies
            - Generated new requirements-dev.txt with hashes

            Auto-generated by dependency update workflow."
            
            git commit -m "$commit_message"
            
            # Push branch
            git push origin "$branch_name"
            
            # Create PR body
            cat > pr_body.md << 'EOF'
            ## Dependency Updates

            This PR updates Python dependencies and GitHub Actions to their latest versions.

            ### Changes:
            - ðŸ“¦ Updated Python development dependencies
            - ðŸ”§ Updated GitHub Actions versions
            - ðŸ”’ Ran security checks on dependencies
            - ðŸ“ Generated new locked requirements

            ### Security:
            - Checked for known vulnerabilities with Safety and pip-audit
            - All dependencies scanned for security issues

            ### Testing:
            - Build tested with updated dependencies
            - Dependency tree validated for conflicts

            **Note**: Please review the changes and run tests before merging.
            EOF
            
            echo "PR_CREATED=true" >> $GITHUB_OUTPUT
            echo "BRANCH_NAME=$branch_name" >> $GITHUB_OUTPUT
          else
            echo "No dependency updates needed"
            echo "PR_CREATED=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub PR
        if: steps.create_pr.outputs.PR_CREATED == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "ðŸ”„ Update Python dependencies ($(date +%Y-%m-%d))" \
            --body-file pr_body.md \
            --label "dependencies" \
            --label "python" \
            --assignee "${{ github.actor }}"

      - name: Upload security reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-reports-python
          path: |
            trustformers-py/safety-report.json
            trustformers-py/audit-report.json
            trustformers-py/current-requirements.txt

  # Update Rust dependencies
  update-rust-dependencies:
    name: Update Rust Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-edit and cargo-audit
        run: |
          cargo install cargo-edit cargo-audit cargo-outdated

      - name: Check current Rust dependencies
        run: |
          echo "## Current Rust Dependencies (trustformers-py)" >> $GITHUB_STEP_SUMMARY
          echo '```toml' >> $GITHUB_STEP_SUMMARY
          cat trustformers-py/Cargo.toml >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Check for outdated dependencies
        working-directory: trustformers-py
        run: |
          echo "## Outdated Dependencies" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cargo outdated >> $GITHUB_STEP_SUMMARY || echo "cargo-outdated failed" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Update dependencies
        working-directory: trustformers-py
        run: |
          # Update PyO3 and related dependencies
          cargo upgrade pyo3 --compatible
          cargo upgrade maturin --compatible
          
          # Update other dependencies
          cargo upgrade serde --compatible
          cargo upgrade tokio --compatible
          cargo upgrade anyhow --compatible
          cargo upgrade thiserror --compatible

      - name: Run security audit
        working-directory: trustformers-py
        run: |
          echo "## Security Audit" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cargo audit >> $GITHUB_STEP_SUMMARY || echo "Security audit found issues" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Test build
        working-directory: trustformers-py
        run: |
          # Test that the project still builds
          cargo check || echo "Build check failed"

      - name: Create Rust dependency PR
        run: |
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "Rust Dependency Update Bot"
          
          # Check if there are changes
          if ! git diff --quiet trustformers-py/Cargo.toml; then
            # Create branch
            branch_name="update-rust-dependencies-py-$(date +%Y%m%d)"
            git checkout -b "$branch_name"
            
            # Add changes
            git add trustformers-py/Cargo.toml
            
            # Commit changes
            git commit -m "Update Rust dependencies for trustformers-py

            - Updated PyO3 and maturin to latest compatible versions
            - Updated core Rust dependencies
            - Ran security audit
            - Verified build compatibility

            Auto-generated by dependency update workflow."
            
            # Push branch
            git push origin "$branch_name"
            
            # Create PR
            cat > rust_pr_body.md << 'EOF'
            ## Rust Dependency Updates (trustformers-py)

            This PR updates Rust dependencies for the Python package to their latest compatible versions.

            ### Changes:
            - ðŸ¦€ Updated PyO3 and maturin
            - ðŸ“¦ Updated core Rust dependencies
            - ðŸ”’ Ran security audit
            - âœ… Verified build compatibility

            ### Security:
            - Checked for known vulnerabilities with cargo-audit
            - All dependencies scanned for security issues

            **Note**: Please test the Python extension build before merging.
            EOF
            
            gh pr create \
              --title "ðŸ¦€ Update Rust dependencies for Python package ($(date +%Y-%m-%d))" \
              --body-file rust_pr_body.md \
              --label "dependencies" \
              --label "rust" \
              --label "python" \
              --assignee "${{ github.actor }}"
          else
            echo "No Rust dependency updates needed for trustformers-py"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Summary
  update-summary:
    name: Update Summary
    runs-on: ubuntu-latest
    needs: [update-python-dependencies, update-rust-dependencies]
    if: always()
    steps:
      - name: Create summary
        run: |
          echo "# Dependency Update Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Status" >> $GITHUB_STEP_SUMMARY
          echo "- **Python Dependencies**: ${{ needs.update-python-dependencies.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Rust Dependencies**: ${{ needs.update-rust-dependencies.result }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Check the workflow logs and created PRs for detailed information." >> $GITHUB_STEP_SUMMARY