name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run nightly tests at 2 AM UTC
    - cron: '0 2 * * *'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # Code quality checks
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    
    - name: Cache cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Check formatting
      run: cargo fmt --all -- --check
    
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    
    - name: Check documentation
      run: cargo doc --all-features --no-deps --document-private-items

  # Build tests across platforms and architectures
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: windows
          - os: macos-latest
            platform: macos
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Install system dependencies (Linux)
      if: matrix.platform == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config
    
    - name: Install system dependencies (macOS)
      if: matrix.platform == 'macos'
      run: |
        brew install pkg-config
    
    - name: Build default features
      run: cargo build --verbose
    
    - name: Build with all features
      run: cargo build --all-features --verbose
    
    - name: Build release
      run: cargo build --release --verbose

  # Comprehensive testing
  test:
    name: Test (${{ matrix.os }}, ${{ matrix.features }})
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        features: 
          - "default"
          - "serving"
          - "cuda"
          - "all-features"
        include:
          - os: ubuntu-latest
            platform: linux
            test_script: "./scripts/test-runner.sh"
          - os: windows-latest
            platform: windows
            test_script: "scripts\\test-runner.bat"
          - os: macos-latest
            platform: macos
            test_script: "./scripts/test-runner.sh"
        exclude:
          # CUDA tests only on Linux for CI
          - os: windows-latest
            features: "cuda"
          - os: macos-latest
            features: "cuda"
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Install system dependencies (Linux)
      if: matrix.platform == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config valgrind
    
    - name: Install system dependencies (macOS)
      if: matrix.platform == 'macos'
      run: |
        brew install pkg-config
    
    - name: Make test script executable (Unix)
      if: matrix.platform != 'windows'
      run: chmod +x scripts/test-runner.sh
    
    - name: Run tests with default features
      if: matrix.features == 'default'
      run: |
        ${{ matrix.test_script }} --ci -f default
    
    - name: Run tests with serving features
      if: matrix.features == 'serving'
      run: |
        ${{ matrix.test_script }} --ci -f serving
    
    - name: Run tests with CUDA features (Linux only)
      if: matrix.features == 'cuda' && matrix.platform == 'linux'
      run: |
        ${{ matrix.test_script }} --ci -f cuda
    
    - name: Run tests with all features
      if: matrix.features == 'all-features'
      run: |
        ${{ matrix.test_script }} --ci --features tokenizers,models,pipelines,serving
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.features }}
        path: |
          test-results/
          coverage/
        retention-days: 30

  # Memory safety testing with sanitizers
  memory_safety:
    name: Memory Safety Tests
    runs-on: ubuntu-latest
    needs: quality
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust nightly
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src
    
    - name: Cache cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-nightly-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config valgrind
    
    - name: Run AddressSanitizer tests
      env:
        RUSTFLAGS: "-Zsanitizer=address"
        ASAN_OPTIONS: "detect_leaks=1:abort_on_error=1"
      run: |
        cargo +nightly test --target x86_64-unknown-linux-gnu --lib
    
    - name: Run LeakSanitizer tests
      env:
        RUSTFLAGS: "-Zsanitizer=leak"
      run: |
        cargo +nightly test --target x86_64-unknown-linux-gnu --lib
    
    - name: Run Valgrind tests
      run: |
        chmod +x scripts/test-runner.sh
        ./scripts/test-runner.sh --memory --ci

  # Performance regression testing
  performance:
    name: Performance Tests
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'schedule' || contains(github.event.pull_request.labels.*.name, 'performance')
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-performance-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config
    
    - name: Run performance tests
      run: |
        chmod +x scripts/test-runner.sh
        ./scripts/test-runner.sh --performance --release --ci
    
    - name: Upload performance results
      uses: actions/upload-artifact@v3
      with:
        name: performance-results
        path: test-results/performance_tests.log

  # Language bindings testing
  bindings:
    name: Language Bindings (${{ matrix.language }})
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        language: [go, python, nodejs]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config
    
    - name: Build C library
      run: cargo build --release
    
    - name: Setup Go
      if: matrix.language == 'go'
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Test Go bindings
      if: matrix.language == 'go'
      run: |
        cd golang
        go mod tidy
        go test -v ./...
    
    - name: Setup Python
      if: matrix.language == 'python'
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Test Python bindings
      if: matrix.language == 'python'
      run: |
        cd python
        pip install -e .
        pip install pytest
        pytest tests/ -v
    
    - name: Setup Node.js
      if: matrix.language == 'nodejs'
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Test Node.js bindings
      if: matrix.language == 'nodejs'
      run: |
        cd nodejs
        npm install
        npm test

  # Security audit
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install cargo-audit
      run: cargo install cargo-audit
    
    - name: Run security audit
      run: cargo audit
    
    - name: Run cargo-deny
      uses: EmbarkStudios/cargo-deny-action@v1

  # Code coverage
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config
    
    - name: Install cargo-tarpaulin
      run: cargo install cargo-tarpaulin
    
    - name: Generate code coverage
      run: |
        cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: cobertura.xml
        fail_ci_if_error: true

  # Release builds and artifacts
  release:
    name: Release Artifacts (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [quality, test, memory_safety]
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            artifact_name: libtrustformers_c.so
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            artifact_name: trustformers_c.dll
          - target: x86_64-apple-darwin
            os: macos-latest
            artifact_name: libtrustformers_c.dylib
          - target: aarch64-apple-darwin
            os: macos-latest
            artifact_name: libtrustformers_c.dylib
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Cache cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Install system dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config
    
    - name: Install system dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install pkg-config
    
    - name: Build release binary
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Create artifact directory
      run: mkdir -p artifacts
    
    - name: Copy artifact (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} artifacts/
    
    - name: Copy artifact (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        copy target\\${{ matrix.target }}\\release\\${{ matrix.artifact_name }} artifacts\\
    
    - name: Upload release artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-${{ matrix.target }}
        path: artifacts/
        retention-days: 90

  # Benchmark comparison
  benchmark:
    name: Benchmark Comparison
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config
    
    - name: Install cargo-criterion
      run: cargo install cargo-criterion
    
    - name: Run benchmarks
      run: cargo criterion --message-format=json > benchmark-results.json
    
    - name: Compare with main branch
      run: |
        git checkout main
        cargo criterion --message-format=json > benchmark-main.json
        # Compare results (would need custom script)
    
    - name: Upload benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-comparison
        path: |
          benchmark-results.json
          benchmark-main.json

  # Deployment to staging (if needed)
  deploy_staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [release]
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    environment: staging
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: release-x86_64-unknown-linux-gnu
    
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment"
        # Add actual deployment steps here

  # Final status check
  status_check:
    name: Status Check
    runs-on: ubuntu-latest
    needs: [quality, test, memory_safety, bindings, security, coverage]
    if: always()
    steps:
    - name: Check all jobs status
      run: |
        if [[ "${{ needs.quality.result }}" != "success" ]]; then
          echo "Quality checks failed"
          exit 1
        fi
        if [[ "${{ needs.test.result }}" != "success" ]]; then
          echo "Tests failed"
          exit 1
        fi
        if [[ "${{ needs.memory_safety.result }}" != "success" ]]; then
          echo "Memory safety tests failed"
          exit 1
        fi
        if [[ "${{ needs.bindings.result }}" != "success" ]]; then
          echo "Language bindings tests failed"
          exit 1
        fi
        if [[ "${{ needs.security.result }}" != "success" ]]; then
          echo "Security audit failed"
          exit 1
        fi
        if [[ "${{ needs.coverage.result }}" != "success" ]]; then
          echo "Coverage analysis failed"
          exit 1
        fi
        echo "All checks passed successfully!"