name: Cross-Platform Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Test suite to run (leave empty for all)'
        required: false
        type: string
      enable_performance_tests:
        description: 'Enable performance tests'
        required: false
        type: boolean
        default: false

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # Test matrix for different platforms and architectures
  test-matrix:
    strategy:
      matrix:
        include:
          # Linux builds
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            rust: stable
            features: ""
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            rust: stable
            features: "cuda,rocm"
          
          # Windows builds
          - os: windows-2022
            target: x86_64-pc-windows-msvc
            rust: stable
            features: ""
          - os: windows-2022
            target: x86_64-pc-windows-msvc
            rust: stable
            features: "cuda"
          
          # macOS builds
          - os: macos-12
            target: x86_64-apple-darwin
            rust: stable
            features: ""
          - os: macos-12
            target: x86_64-apple-darwin
            rust: stable
            features: "metal"
          - os: macos-14
            target: aarch64-apple-darwin
            rust: stable
            features: ""
          - os: macos-14
            target: aarch64-apple-darwin
            rust: stable
            features: "metal"

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        targets: ${{ matrix.target }}

    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ matrix.target }}-
          ${{ runner.os }}-cargo-

    # Platform-specific dependencies
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          pkg-config \
          libc6-dev \
          valgrind \
          clang \
          llvm

    - name: Install Windows dependencies
      if: runner.os == 'Windows'
      run: |
        # Install LLVM for bindgen
        choco install llvm

    - name: Install macOS dependencies
      if: runner.os == 'macOS'
      run: |
        brew install llvm

    # Hardware acceleration setup
    - name: Setup CUDA (Linux)
      if: runner.os == 'Linux' && contains(matrix.features, 'cuda')
      uses: Jimver/cuda-toolkit@v0.2.11
      with:
        cuda: '12.2'

    - name: Setup ROCm (Linux)
      if: runner.os == 'Linux' && contains(matrix.features, 'rocm')
      run: |
        wget -q -O - https://repo.radeon.com/rocm/rocm.gpg.key | sudo apt-key add -
        echo 'deb [arch=amd64] https://repo.radeon.com/rocm/apt/5.4.3/ ubuntu main' | sudo tee /etc/apt/sources.list.d/rocm.list
        sudo apt-get update
        sudo apt-get install -y rocm-dev hip-dev

    - name: Setup Metal (macOS)
      if: runner.os == 'macOS' && contains(matrix.features, 'metal')
      run: |
        # Metal is built into macOS, just verify Xcode tools
        xcode-select --install || true

    # Language binding dependencies
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    # Install test automation dependencies
    - name: Install Python test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pytest-xdist requests

    # Build and test
    - name: Build TrustformeRS (Debug)
      run: |
        cargo build --target ${{ matrix.target }} --features "${{ matrix.features }}"

    - name: Build TrustformeRS (Release)
      run: |
        cargo build --release --target ${{ matrix.target }} --features "${{ matrix.features }}"

    - name: Run unit tests
      run: |
        cargo test --target ${{ matrix.target }} --features "${{ matrix.features }}" -- --nocapture

    - name: Run integration tests
      run: |
        cargo test --release --target ${{ matrix.target }} --features "${{ matrix.features }}" --test integration_tests

    # Memory safety tests (Linux only)
    - name: Run Valgrind tests
      if: runner.os == 'Linux'
      run: |
        chmod +x scripts/valgrind_test.sh
        ./scripts/valgrind_test.sh

    - name: Run AddressSanitizer tests
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        chmod +x scripts/asan_test.sh
        ./scripts/asan_test.sh

    # Language binding tests
    - name: Test Python bindings
      working-directory: python
      run: |
        pip install -e .
        python -m pytest tests/ -v --tb=short

    - name: Test Node.js bindings
      working-directory: nodejs
      run: |
        npm install
        npm test

    - name: Test Go bindings
      working-directory: golang
      run: |
        go mod tidy
        go test -v ./...

    - name: Test Java bindings
      working-directory: java
      run: |
        mvn test

    - name: Test C# bindings
      working-directory: csharp
      run: |
        dotnet restore
        dotnet test --verbosity normal

    # Performance tests (optional)
    - name: Run performance tests
      if: github.event.inputs.enable_performance_tests == 'true' || github.event_name == 'schedule'
      run: |
        cargo bench --target ${{ matrix.target }} --features "${{ matrix.features }}"

    # Property-based tests
    - name: Run property-based tests
      run: |
        cargo test --release --target ${{ matrix.target }} --features "${{ matrix.features }}" --test property_based_tests

    # Cross-platform test automation
    - name: Run automated test suite
      run: |
        python scripts/test-automation.py \
          --suite "Core Functionality" \
          --suite "Memory Safety" \
          --suite "Language Bindings" \
          --output test-results/automated-${{ matrix.os }}-${{ matrix.target }} \
          --parallel \
          --verbose

    # Upload test results
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.target }}
        path: |
          test-results/
          target/criterion/
          *.log

    # Code coverage (Linux only)
    - name: Generate code coverage
      if: runner.os == 'Linux' && matrix.target == 'x86_64-unknown-linux-gnu' && !contains(matrix.features, 'cuda')
      run: |
        cargo install cargo-tarpaulin
        cargo tarpaulin --target ${{ matrix.target }} --features "${{ matrix.features }}" --out xml

    - name: Upload coverage to Codecov
      if: runner.os == 'Linux' && matrix.target == 'x86_64-unknown-linux-gnu' && !contains(matrix.features, 'cuda')
      uses: codecov/codecov-action@v3
      with:
        file: cobertura.xml
        flags: unittests
        name: codecov-umbrella

  # Security audit
  security-audit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install cargo-audit
      run: cargo install cargo-audit

    - name: Run security audit
      run: cargo audit

  # Dependency check
  dependency-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Check dependencies
      run: |
        cargo tree --duplicates
        cargo outdated || true

  # Build documentation
  documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build documentation
      run: |
        cargo doc --all-features --no-deps

    - name: Deploy documentation
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc

  # Performance regression testing
  performance-regression:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install critcmp
      run: cargo install critcmp

    - name: Run baseline benchmarks (main branch)
      run: |
        git checkout main
        cargo bench --bench inference_benchmark -- --save-baseline main

    - name: Run current benchmarks (PR branch)
      run: |
        git checkout ${{ github.head_ref }}
        cargo bench --bench inference_benchmark -- --save-baseline current

    - name: Compare benchmarks
      run: |
        critcmp main current

  # Fuzz testing
  fuzz-testing:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@nightly

    - name: Install cargo-fuzz
      run: cargo install cargo-fuzz

    - name: Run fuzz tests
      run: |
        if [ -d fuzz ]; then
          cargo fuzz run fuzz_target_1 -- -max_total_time=300
        fi

  # Integration with external services
  external-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [huggingface, onnx, tensorrt]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Test ${{ matrix.service }} integration
      run: |
        cargo test --release --features "${{ matrix.service }}" integration_${{ matrix.service }}

  # Summary job
  test-summary:
    runs-on: ubuntu-latest
    needs: [test-matrix, security-audit, dependency-check]
    if: always()
    steps:
    - name: Check test results
      run: |
        if [[ "${{ needs.test-matrix.result }}" == "failure" ]]; then
          echo "❌ Test matrix failed"
          exit 1
        elif [[ "${{ needs.security-audit.result }}" == "failure" ]]; then
          echo "❌ Security audit failed"
          exit 1
        elif [[ "${{ needs.dependency-check.result }}" == "failure" ]]; then
          echo "❌ Dependency check failed"
          exit 1
        else
          echo "✅ All tests passed"
        fi

    - name: Generate summary
      run: |
        echo "## Test Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Platform Matrix**: ${{ needs.test-matrix.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Security Audit**: ${{ needs.security-audit.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Dependency Check**: ${{ needs.dependency-check.result }}" >> $GITHUB_STEP_SUMMARY